### ISSUE TITLE
License terms violation

### ISSUE THREAD

**Issue by aqrln** [in-wave/Wave#2]
The MIT license, under which terms and conditions Impress Application Server is redistributed, states:

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

It is okay to change the name in your fork, but the original LICENSE file must be either merged into your LICENSE file or copied under a new name (consider `LICENSE-impress` to be consistent with other files you copy and rename).

**Comment by dimon-durak** [comment]
@aqrln я так понял, файл лицензии IAS появился с версии 0.4
Подправил скриптик, сейчас он оставляет оригинальную лицензию с под именем `LICENSE-impress`

PS
Фух, честно - от сердца отлегло... Сомнительное действие по переименовыванию оказалось вроде как норм.
 
PPS
И кстати, выяснилось, что в win для установки Impress 0.4 нужны админские права (вроде бы из  симлинков, которые создаёт install.js). Предыдущая версия ставилась без админа.

PPPS
Забегая вперёд - а нет ли у Impress планов перехода на typescript?

**Comment by aqrln** [comment]
@dimon-durak да, с 0.4. Действие по своей сути всё равно остаётся сомнительным с этической точки зрения, но при наличии оригинальной лицензии — хотя бы законным :) По поводу Windows ничего не скажу, надо проверять. Планов перехода на TypeScript нет.

**Comment by dimon-durak** [comment]
@aqrln ну этика - моё больное место )

Impress действительно крутой проект - это я уже давно понял.
Пока хочу разобраться с PWA (front-end), а затем уже плотно заняться освоением в деталях IAS, и надеюсь когда подрасту, смогу помочь хоть чем-то.

И да, в винде для установки IAS нужен админ - это я выяснил сегодня
